apiVersion: apps/v1
kind: Deployment
metadata:
  name: devforge-backend
  labels:
    app: devforge
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devforge
      tier: backend
  template:
    metadata:
      labels:
        app: devforge
        tier: backend
    spec:
      containers:
      - name: devforge-backend
        image: devforge/devforge-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
