apiVersion: v1
kind: Service
metadata:
  name: devforge-backend
  labels:
    app: devforge
    tier: backend
spec:
  selector:
    app: devforge
    tier: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP # Internal service, accessible only within the cluster
