apiVersion: v1
kind: Service
metadata:
  name: devforge-frontend
  labels:
    app: devforge
    tier: frontend
spec:
  selector:
    app: devforge
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer # Use LoadBalancer for cloud deployments or NodePort for local/on-prem
