apiVersion: apps/v1
kind: Deployment
metadata:
  name: devforge-frontend
  labels:
    app: devforge
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devforge
      tier: frontend
  template:
    metadata:
      labels:
        app: devforge
        tier: frontend
    spec:
      containers:
      - name: devforge-frontend
        image: devforge/devforge-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: REACT_APP_API_URL
          value: "http://devforge-backend:5000/api"
        - name: NODE_ENV
          value: "production"
