apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded MongoDB connection string (replace with your actual encoded connection string)
  connection-string: bW9uZ29kYitzcnY6Ly9tdmFydW5tYXRoaTIwMDQ6NDU0NkBkZXZmb3JnZS5yNmp4ZGRtLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1kZXZmb3JnZQo=
